# Generated by Django 4.0.5 on 2022-06-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
