# Generated by Django 4.0.5 on 2022-06-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_location_expenses_new_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='suburb',
        ),
    ]
