# Generated by Django 4.0.5 on 2022-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_location_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='short_tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
