# Generated by Django 4.0.5 on 2022-06-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_expenses_short_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='new_category',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='new_location',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.location'),
        ),
    ]
